version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Sao_Paulo
      - VERSION=docker
      - PLEX_CLAIM= #optional
    ports:
      - 32400:32400
    volumes:
      - $HOME/home_media/plex:/config
      - /torrents/tvseries:/tv
      - /torrents:/movies
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.100

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
    volumes:
      - $HOME/home_media/qbittorrent:/config
      - /torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.101

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true #optional
    volumes:
      - $HOME/home_media/jackett:/config
      - $HOME/home_media/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.102

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/prowlarr:/config
    ports:
      - 9696:9696
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.103

  sonarr:
  image: lscr.io/linuxserver/sonarr:latest
  container_name: sonarr
  environment:
    - PUID=$(id -u)
    - PGID=$(id -g)
    - TZ=America/Sao_Paulo
  volumes:
    - $HOME/home_media/sonarr:/config
    - /torrents/tvseries:/tv #optional
    - /torrents:/downloads #optional
  ports:
    - 8989:8989
  restart: always #optional
  networks:
    media:
        ipv4_address: 172.18.0.104

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/radarr:/config
      - /torrents/movies:/movies #optional
      - /torrents:/downloads #optional
    ports:
      - 7878:7878
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.105

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Sao_Paulo
    volumes:
      - $HOME/home_media/bazarr:/config
      - /torrents:/movies #optional
      - /torrents/tvseries:/tv #optional
    ports:
      - 6767:6767
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.106

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.6
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.107

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    volumes:
      - $HOME/home_media/tautulli:/config
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=<timezone>
    ports:
      - 8181:8181
    restart: always #optional
    networks:
      media:
        ipv4_address: 172.18.0.109

networks:
  media:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 192.168.200.5
